/**
 * The committed contract barrel (R15). Everything that crosses the network is
 * imported from `@/contracts` and nowhere else.
 *
 * `./api` and `./ws` are generated by `make contracts` from the committed
 * artefacts `contracts/openapi.json` and `contracts/ws-schema.json`; they are
 * git-ignored and never hand-edited. This file adds no shapes of its own — it
 * only names the generated ones and derives aliases from them, so a hand-written
 * network type cannot exist in `web/src/`.
 */
import type { components } from './api';

export type { components, operations, paths } from './api';

type Schemas = components['schemas'];

/* ── REST models (openapi.json) ─────────────────────────────────────────── */
export type Plant = Schemas['Plant'];
export type ChannelSpec = Schemas['ChannelSpec'];
export type MachineSummary = Schemas['MachineSummary'];
export type MachineDetail = Schemas['MachineDetail'];
export type TelemetrySeries = Schemas['TelemetrySeries'];
export type RiskSeries = Schemas['RiskSeries'];
export type AlertMarker = Schemas['AlertMarker'];
export type Alert = Schemas['Alert'];
export type AlertPage = Schemas['AlertPage'];
export type Explanation = Schemas['Explanation'];
export type ShapContribution = Schemas['ShapContribution'];
export type SentenceSpan = Schemas['SentenceSpan'];
export type GlobalImportance = Schemas['GlobalImportance'];
export type ImportanceFeature = Schemas['ImportanceFeature'];
export type ImportancePoint = Schemas['ImportancePoint'];
export type ModelComparison = Schemas['ModelComparison'];
export type FeatureDisagreement = Schemas['FeatureDisagreement'];
export type ModelInfo = Schemas['ModelInfo'];
export type PlantSnapshot = Schemas['PlantSnapshot'];
export type WhatIfRequest = Schemas['WhatIfRequest'];
export type WhatIfResponse = Schemas['WhatIfResponse'];
export type ConfigResponse = Schemas['ConfigResponse'];
export type ConfigPatch = Schemas['ConfigPatch'];
export type HealthResponse = Schemas['HealthResponse'];
export type ReplayState = Schemas['ReplayState'];
export type ReplayCommand = Schemas['ReplayCommand'];
export type Problem = Schemas['Problem'];

/* ── WebSocket frames (ws-schema.json) ──────────────────────────────────── */
export type {
  AlertFrame,
  ClientFrame,
  ConfigFrame,
  ErrorFrame,
  ExplanationFrame,
  HelloFrame,
  MachineSnapshot,
  PingFrame,
  ReplayStateFrame,
  RiskFrame,
  RiskUpdate,
  ServerFrame,
  SnapshotFrame,
  TelemetryFrame,
  TelemetryUpdate,
  TopFeature,
} from './ws';

import type { ServerFrame } from './ws';

/* ── Aliases derived from the generated shapes, never re-declared ───────── */
export type PlantId = Plant['plant_id'];
export type MachineStatus = MachineSummary['status'];
export type AlertSeverity = Alert['severity'];
export type ModelKind = Explanation['model_kind'];
export type ShapSpace = Explanation['shap_space'];
export type ReplayCommandName = ReplayCommand['command'];
/** The allowed replay multipliers, straight off the contract (frontend.md §1.1). */
export type Speed = NonNullable<ReplayCommand['speed']>;
/** The `type` discriminator of every server frame the protocol defines. */
export type ServerFrameType = ServerFrame['type'];
/** A single machine's scalar values inside a batched `telemetry` frame. */
export type ConfigValue = ConfigResponse['values'][string];
