"""``model_card.md``: what this model is, what it is not, and what it cost.

One card per registry version, written by ``train.py`` from the manifest and the
held-out metrics, so it can never describe a different artefact than the one it
sits next to. GOAL lists a model card among the graded artefacts;
``docs/ARCHITECTURE.md`` links to these files rather than restating them.

The card states two things the rest of the system depends on and that a reader
must not have to infer: that the probability it reports is the only probability
in the system (no calibrator anywhere — R16, ADR-016), and that SHAP
attributions are associations, not causes (R13).
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence

from xpm.contracts.common import PlantId
from xpm.features.registry import feature_meta
from xpm.model.registry import Manifest

__all__ = ["CAUSATION_CAVEAT", "render_model_card"]

#: The honesty caveat GOAL requires next to every explanation artefact. The
#: dashboard's copy is ``explanation.caveat`` in settings.yaml; this is the
#: document-side statement of the same fact.
CAUSATION_CAVEAT: str = (
    "SHAP attributions describe how this model arrived at this score. They are "
    "associations learned from historical data, not proof of physical cause."
)

_DATASET_NOTES: Mapping[str, str] = {
    "ai4i": (
        "AI4I 2020 (UCI id 601), 10 000 product records dealt round-robin into 12 "
        "virtual machines at one row per 5 minutes of dataset time. Treating "
        "i.i.d. product records as a per-machine time series is a simulation "
        "convenience (ADR-024): windowed features describe a synthetic history, "
        "which is why the ablation is reported per plant and read with care."
    ),
    "ims": (
        "NASA IMS bearing test set 2: 984 vibration snapshots x 4 bearings at one "
        "file per 10 minutes, band energies from a Welch PSD. `failure_imminent` "
        "labels the last 24 h before end-of-record on the one bearing that "
        "actually fails (ADR-023), so every positive row in this plant belongs to "
        "`ims-01`."
    ),
}


def _top_feature_rows(plant_id: PlantId, importances: Mapping[str, float], limit: int) -> list[str]:
    meta = feature_meta(plant_id)
    ranked = sorted(importances.items(), key=lambda item: item[1], reverse=True)[:limit]
    rows = ["| rank | feature | display name | importance |", "|---|---|---|---|"]
    for position, (name, value) in enumerate(ranked, start=1):
        display = meta[name].display_name if name in meta else name
        rows.append(f"| {position} | `{name}` | {display} | {value:.4f} |")
    return rows


def render_model_card(
    manifest: Manifest,
    *,
    metrics: Mapping[str, float],
    importances: Mapping[str, float],
    top_k: int,
    caveats: Sequence[str] = (),
) -> str:
    """The Markdown body of one version's ``model_card.md``."""
    lines: list[str] = [
        f"# Model card — `{manifest.model_id}` ({manifest.plant_id})",
        "",
        "Machine-generated by `scripts/train.py`. Regenerate with `make train`.",
        "",
        "## Identity",
        "",
        f"- Model id: `{manifest.model_id}` (family `{manifest.family}`, "
        f"version `{manifest.version}`)",
        f"- Plant: `{manifest.plant_id}`",
        f"- Trained at: `{manifest.trained_at}`",
        f"- Training run id: `{manifest.train_run_id}`",
        f"- Seed: `{manifest.seed}`",
        f"- Code: `{manifest.code_sha or 'not a git checkout'}`"
        f"{' (working tree dirty)' if manifest.code_dirty else ''}",
        f"- Processed data digest: `{manifest.data_sha256}`",
        f"- Feature order digest: `{manifest.feature_names_sha256}`",
        "",
        "## Intended use",
        "",
        "Scores one machine's windowed feature vector into a failure probability "
        "for the explainable-maintenance demo in this repository. It is trained on "
        "public benchmark data replayed as a simulation; it is not fit for "
        "operating real plant equipment.",
        "",
        "## Data",
        "",
        f"- {_DATASET_NOTES[manifest.plant_id]}",
        f"- Label column: `{manifest.label}`",
        f"- Split: `{manifest.split}`, first held-out instant `{manifest.split_ts}`",
        f"- Training window: `{manifest.train_window_start}` to `{manifest.train_window_end}`",
        f"- Rows: {manifest.n_train_rows} train ({manifest.train_positives} positive), "
        f"{manifest.n_test_rows} held out ({manifest.test_positives} positive)",
        f"- Warm-up rows dropped before splitting: {manifest.warmup_rows_dropped}",
        "",
        "## Features",
        "",
        f"- {manifest.n_features} features, ordered by `xpm.features.registry`; "
        "`feature_names.json` beside this card is that order and serving refuses "
        "a model whose order disagrees with the code.",
        "",
        *_top_feature_rows(manifest.plant_id, importances, top_k),
        "",
        "## Training",
        "",
        *(f"- `{key}`: `{value}`" for key, value in sorted(manifest.hyperparameters.items())),
        *(f"- `{key}`: `{value}`" for key, value in sorted(manifest.library_versions.items())),
        "",
        "## Held-out metrics",
        "",
        "| metric | value |",
        "|---|---|",
        *(f"| `{key}` | {value:.4f} |" for key, value in sorted(metrics.items())),
        "",
        "Full tables, the confusion matrix and the calibration diagnostic are in "
        "`docs/EVALUATION.md`.",
        "",
        "## Limitations and honesty",
        "",
        "- **One probability.** The number above is the model's own output. No "
        "isotonic or Platt calibrator sits between it and the alert threshold, the "
        "dashboard, or the SHAP waterfall (R16, ADR-016). Calibration is measured "
        "in `docs/EVALUATION.md`, not applied.",
        f"- **{CAUSATION_CAVEAT}**",
        f"- The SHAP background is {manifest.background_rows} rows sampled from the "
        f"training split with seed `{manifest.background_seed}`; every base value "
        "in the dashboard is relative to that sample.",
        *(f"- {caveat}" for caveat in caveats),
        "",
    ]
    return "\n".join(lines).rstrip("\n") + "\n"
